export const forbiddenWords = [
  // Kasar / makian umum
  'anjing', 'anjhing', 'anjg', 'anjgk', 'babi', 'babbii', 'bangsat', 'bangzzat', 'tai', 't4i', 'taai',
  'kontol', 'kntl', 'k0ntol', 'memek', 'memekk', 'puki', 'pukii', 'bajingan', 'bajingann', 'setan', 's3tan',
  'goblok', 'goblokk', 'tolol', 't0l0l', 'idiot', 'sialan', 'brengsek', 'bodoh', 'bod0h', 'gila', 'gilaa', 'kampungan', 'kampungg', 'fuck', 'fak', 'dafuck', 'dafak', 'bitch',
  'cupu', 'cupuu', 'jelek', 'jlek', 'payah', 'pay4h', 'pecundang',

  // Seksual / pornografi
  'sex', 'sexx', 'porn', 'porno', 'pornografi', 'vagina', 'vaginah', 'penis', 'peniss', 'masturbasi', 'masturbate', 'bokep', 'tot', 'kentot', 'ntot', 'ngentu', 'titit', 'titid',
  'ngentot', 'ngntot', 'ngocok', 'ngisk', 'ngisep', 'ngewe', 'bokep', 'pornoid', 'pornoan', 'forno', 'phorno', 'fhorno', 'ngntd', 'ntod', 'peler', 'manuk', 'asshole', 'konthol', 'khontol', 'kintil', 'khintil', 'kuntul', 'khuntul','kinthil', 'kunthul',

  // Perilaku kriminal / negatif
  'sampah', 'maling', 'pencuri', 'korup', 'koruptor', 'fitnah', 'penipu', 'curang', 'bunuh', 'pembunuh', 'killer',

  // Slang dan variasi lain
  'bego', 'bodohhh', 'bajigg', 'brengsekkk', 'tholol', 'kampungann', 'cupuuy', 'payahhh', 'b2', 'crot', 'ancrit', 'setan', 'iblis', 'penyihir', 'penjahat', 'kanjut', 'kanjud',

  // Ras / SARA (variasi umum)
  'cino', 'cina', 'cinaa', 'cinoo', 'nazi', 'komunis', 'komunisme', 'nasionalis', 'sosialis', 'nasionalisme', 'sosialisme', 'fasis', 'fasisme', 'politik', 'partai', 'dasar hama', 'bungul', 'beleng',
  'goblokcina', 'goblokcinaa', 
  'bule', 'buleee', 
  'arab', 'arabb', 'indon', 'indones', 'indo', 'indoos', 'malaysial', 'malingsial', 'tobrut', 'tobrud', 'sipit',
  'hitam', 'item', 'itemm', 
  'goblokhitam', 'kampret', 'kamprett', 'kafir', 'kafirr', 'jawir', 'ireng', 
   'anal',
    'anjay',
    'anjing',
    'anjir',
    'anjrit',
    'anjrot',
    'anying',
    'ashu',
    'asoe',
    'asshole',
    'asu',
    'asyu',
    'babi',
    'bacol',
    'bacot',
    'bajingan',
    'banci',
    'bangke',
    'bangsat',
    'bacot',
    'bastard',
    'basterds',
    'basterdz',
    'bdsm',
    'bego',
    'bejad',
    'bejat',
    'beloon',
    'bencong',
    'berak',
    'biadap',
    'biatch',
    'bikini',
    'birahi',
    'bitch',
    'bloon',
    'blowjob',
    'bodat',
    'bodoh',
    'bokep',
    'bokong',
    'bondage',
    'breast',
    'brengsek',
    'bugil',
    'celeng',
    'clit',
    'cock',
    'cocot',
    'cocote',
    'cok',
    'colai',
    'colay',
    'coli',
    'colmek',
    'congor',
    'creampie',
    'creamypie',
    'cuk',
    'cukima',
    'cukimai',
    'cukimay',
    'damn',
    'dancok',
    'dancuk',
    'deepthroat',
    'dick',
    'dildo',
    'doggystyle',
    'ejackulate',
    'ejakulate',
    'entot',
    'entotan',
    'erection',
    'erotic',
    'ewe',
    'fak',
    'fetish',
    'flikker',
    'footjob',
    'foreskin',
    'foursome',
    'fuck',
    'fucker',
    'fucking',
    'gay',
    'gembel',
    'genital',
    'gigolo',
    'goblog',
    'goblok',
    'gspot',
    'handjob',
    'hardcore',
    'hentai',
    'hate',
    'hell',
    'homo',
    'horny',
    'idiot',
    'incest',
    'itil',
    'jablai',
    'jablay',
    'jancok',
    'jancuk',
    'jembut',
    'jiancok',
    'jilmek',
    'kafir',
    'kampret',
    'kancut',
    'kanjut',
    'kelentit',
    'kenthu',
    'kentu',
    'keparat',
    'kimak',
    'kintil',
    'kirik',
    'klimak',
    'klimax',
    'klitoris',
    'kontol',
    'kopet',
    'koplok',
    'kunyuk',
    'lacur',
    'labia',
    'laknat',
    'lesbi',
    'lolita',
    'lonte',
    'masterbate',
    'meki',
    'memek',
    'mesum',
    'naked',
    'nenen',
    'ngecrot',
    'ngegay',
    'ngentot',
    'ngewe',
    'nggateli',
    'ngocok',
    'ngulum',
    'nigga',
    'nyepong',
    'orgasm',
    'pantat',
    'pantek',
    'panthek',
    'pedophilia',
    'pedo',
    'pedofil',
    'peju',
    'pelacur',
    'pelakor',
    'peler',
    'pemerkosaan',
    'penetration',
    'penis',
    'pentil',
    'pepek',
    'piss',
    'porn',
    'puki',
    'pukima',
    'pukimae',
    'pukimak',
    'pukimay',
    'pussy',
    'racist',
    'recktum',
    'rectum',
    'sadism',
    'sadist',
    'saiton',
    'scrotum',
    'seks',
    'sempak',
    'senggama',
    'sepong',
    'setan',
    'setubuh',
    'sex',
    'shit',
    'shiz',
    'shyt',
    'silit',
    'sodomi',
    'sodomy',
    'sperm',
    'squirt',
    'suck',
    'suicide',
    'syaithon',
    'taek',
    'tai',
    'taik',
    'telanjang',
    'telek',
    'tempek',
    'tempik',
    'tetek',
    'threesome',
    'titit',
    'togel',
    'toket',
    'tolol',
    'tusbol',
    'vagiina',
    'vagina',
    'vajina',
    'vibrator',
    'vullva',
    'vulva',
    'wtf'
];

