export const requiredWords = [
  // Umum pertanian
  "pertanian",
  "tumbuhan",
  "agrikultur",
  "budidaya",
  "tanaman",
  "lahan",
  "petani",
  "panen",
  "pasca panen",
  "produksi",
  "produktifitas",

  // Tanaman & komoditas
  "padi",
  "jagung",
  "kedelai",
  "cabai",
  "tomat",
  "bawang",
  "kentang",
  "singkong",
  "ubi",
  "sayuran",
  "buah",
  "hortikultura",
  "perkebunan",
  "kelapa",
  "sawit",
  "kakao",
  "kopi",
  "teh",
  "tebu",
  "pepaya",
  "pisang",
  "mangga",
  "jeruk",

  // Media tanam & tanah
  "tanah",
  "media tanam",
  "humus",
  "kompos",
  "pupuk",
  "pupuk organik",
  "pupuk anorganik",
  "pupuk kandang",
  "unsur hara",
  "nitrogen",
  "fosfor",
  "kalium",
  "ph tanah",

  // Air & irigasi
  "air",
  "irigasi",
  "drainase",
  "pengairan",
  "curah hujan",
  "kelembaban",
  "embun",

  // Benih & pembibitan
  "benih",
  "bibit",
  "pembibitan",
  "persemaian",
  "varietas",
  "hibrida",

  // Hama & penyakit
  "hama",
  "penyakit tanaman",
  "jamur",
  "bakteri",
  "virus",
  "pestisida",
  "insektisida",
  "fungisida",
  "herbisida",
  "pengendalian hama",
  "pengendalian hayati",

  // Teknik budidaya
  "penanaman",
  "pemupukan",
  "penyiraman",
  "pemangkasan",
  "tumpangsari",
  "monokultur",
  "polikultur",
  "mulsa",

  // Teknologi pertanian
  "teknologi pertanian",
  "smart farming",
  "precision farming",
  "iot",
  "sensor",
  "otomatisasi",
  "drone",
  "data cuaca",
  "prediksi cuaca",
  "alat",

  // Sistem tanam modern
  "hidroponik",
  "aeroponik",
  "akuaponik",
  "greenhouse",
  "rumah kaca",
  "vertical farming",

  // Lingkungan & keberlanjutan
  "pertanian berkelanjutan",
  "agroekologi",
  "organik",
  "konservasi",
  "lingkungan",
  "iklim",
  "perubahan iklim",

  // Manajemen & ekonomi
  "manajemen pertanian",
  "agribisnis",
  "rantai pasok",
  "distribusi",
  "pemasaran",
  "harga",
  "biaya produksi",
  "keuntungan",

  // Lain-lain
  "edukasi pertanian",
  "penyuluhan",
  "pelatihan",
  "penelitian",
  "tropis",
  "inovasi"
];
